--Trackademic project
-- Fanny Giraldo
-- Oscar Suarez

CREATE TABLE COUNTRIES (
    code  INTEGER NOT NULL,
    name  VARCHAR(20) NOT NULL
);

ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRIES_PK PRIMARY KEY (code);


CREATE TABLE CONTRACT_TYPES (
    name VARCHAR(30) NOT NULL
);

ALTER TABLE CONTRACT_TYPES ADD CONSTRAINT CONTRACT_TYPES_PK PRIMARY KEY (name);

CREATE TABLE EMPLOYEE_TYPES (
    name VARCHAR(30) NOT NULL
);

ALTER TABLE EMPLOYEE_TYPES ADD CONSTRAINT EMPLOYEE_TYPES_PK PRIMARY KEY (name);
-- Intermedios
CREATE TABLE DEPARTMENTS (
    code      INTEGER NOT NULL,
    name      VARCHAR(20) NOT NULL,
    country_code INTEGER NOT NULL
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPARTMENTS_PK PRIMARY KEY (code);

CREATE TABLE CITIES (
    code       INTEGER NOT NULL,
    name       VARCHAR(20) NOT NULL,
    dept_code  INTEGER NOT NULL
);

ALTER TABLE CITIES ADD CONSTRAINT CITIES_PK PRIMARY KEY (code);

CREATE TABLE FACULTIES (
    code         INTEGER NOT NULL,
    name         VARCHAR(20) NOT NULL,
    location     VARCHAR(15) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    dean_id      VARCHAR(15)
);

CREATE UNIQUE INDEX FACULTIES__IDX ON FACULTIES (dean_id ASC);

ALTER TABLE FACULTIES ADD CONSTRAINT FACULTIES_PK PRIMARY KEY (code);

CREATE TABLE CAMPUSES (
    code       INTEGER NOT NULL,
    name       VARCHAR(20),
    city_code  INTEGER NOT NULL
);

ALTER TABLE CAMPUSES ADD CONSTRAINT CAMPUSES_PK PRIMARY KEY (code);

-- Dependientes
CREATE TABLE EMPLOYEES (
    id                  VARCHAR(15) NOT NULL,
    first_name          VARCHAR(30) NOT NULL,
    last_name           VARCHAR(30) NOT NULL,
    email               VARCHAR(30) NOT NULL,
    contract_type       VARCHAR(30) NOT NULL,
    employee_type       VARCHAR(30) NOT NULL,
    faculty_code        INTEGER NOT NULL,
    campus_code         INTEGER NOT NULL,
    birth_place_code    INTEGER NOT NULL
);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY (id);

CREATE TABLE AREAS (
    code              INTEGER NOT NULL,
    name              VARCHAR(20) NOT NULL,
    faculty_code      INTEGER NOT NULL,
    coordinator_id    VARCHAR(15) NOT NULL
);

CREATE UNIQUE INDEX AREAS__IDX ON AREAS (coordinator_id ASC);

ALTER TABLE AREAS ADD CONSTRAINT AREAS_PK PRIMARY KEY (code);

CREATE TABLE PROGRAMS (
    code        INTEGER NOT NULL,
    name        VARCHAR(40) NOT NULL,
    area_code   INTEGER NOT NULL
);

ALTER TABLE PROGRAMS ADD CONSTRAINT PROGRAMS_PK PRIMARY KEY (code);

CREATE TABLE SUBJECTS (
    code            VARCHAR(10) NOT NULL,
    name            VARCHAR(30) NOT NULL,
    program_code    INTEGER NOT NULL
);

ALTER TABLE SUBJECTS ADD CONSTRAINT SUBJECTS_PK PRIMARY KEY (code);

CREATE TABLE GROUPS (
    number          INTEGER NOT NULL,
    semester        VARCHAR(6) NOT NULL,
    subject_code    VARCHAR(10) NOT NULL,
    professor_id    VARCHAR(15) NOT NULL
);

ALTER TABLE GROUPS ADD CONSTRAINT GROUPS_PK PRIMARY KEY (number, subject_code, semester);

-- DEPARTMENTS
ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPARTMENTS_COUNTRIES_FK
FOREIGN KEY (country_code) REFERENCES COUNTRIES (code);

-- CITIES
ALTER TABLE CITIES
ADD CONSTRAINT CITIES_DEPARTMENTS_FK
FOREIGN KEY (dept_code) REFERENCES DEPARTMENTS (code);

-- CAMPUSES
ALTER TABLE CAMPUSES
ADD CONSTRAINT CAMPUSES_CITIES_FK
FOREIGN KEY (city_code) REFERENCES CITIES (code);

-- FACULTIES
ALTER TABLE FACULTIES
ADD CONSTRAINT FACULTIES_EMPLOYEES_FK
FOREIGN KEY (dean_id) REFERENCES EMPLOYEES (id);

-- EMPLOYEES
ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_CONTRACT_TYPES_FK
FOREIGN KEY (contract_type) REFERENCES CONTRACT_TYPES (name);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_EMPLOYEE_TYPES_FK
FOREIGN KEY (employee_type) REFERENCES EMPLOYEE_TYPES (name);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_FACULTIES_FK
FOREIGN KEY (faculty_code) REFERENCES FACULTIES (code);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_CAMPUSES_FK
FOREIGN KEY (campus_code) REFERENCES CAMPUSES (code);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_CITIES_FK
FOREIGN KEY (birth_place_code) REFERENCES CITIES (code);

-- AREAS
ALTER TABLE AREAS
ADD CONSTRAINT AREAS_EMPLOYEES_FK
FOREIGN KEY (coordinator_id) REFERENCES EMPLOYEES (id);

ALTER TABLE AREAS
ADD CONSTRAINT AREAS_FACULTIES_FK
FOREIGN KEY (faculty_code) REFERENCES FACULTIES (code);

-- PROGRAMS
ALTER TABLE PROGRAMS
ADD CONSTRAINT PROGRAMS_AREAS_FK
FOREIGN KEY (area_code) REFERENCES AREAS (code);

-- SUBJECTS
ALTER TABLE SUBJECTS
ADD CONSTRAINT SUBJECTS_PROGRAMS_FK
FOREIGN KEY (program_code) REFERENCES PROGRAMS (code);

-- GROUPS
ALTER TABLE GROUPS
ADD CONSTRAINT GROUPS_SUBJECTS_FK
FOREIGN KEY (subject_code) REFERENCES SUBJECTS (code);

ALTER TABLE GROUPS
ADD CONSTRAINT GROUPS_EMPLOYEES_FK
FOREIGN KEY (professor_id) REFERENCES EMPLOYEES (id);

